services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Qwerty1337!
      POSTGRES_DB: InPrompts
    ports:
      - "5432:5432"
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  papercut:
    image: jijiechen/papercut
    restart: always
    ports:
      - "25:25"
      - "37408:37408"
  mongo_email:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  eventbus-mq:
    image: rabbitmq:3-management
    container_name: eventbus-mq
    hostname: eventbus-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/lib/rabbitmq
