// <auto-generated />
using InPrompts.Prompts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InPrompts.Prompts.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PromptsDbContext))]
    [Migration("20240625002100_InitialPrompts")]
    partial class InitialPrompts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Prompts")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InPrompts.Prompts.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DownVotes")
                        .HasColumnType("integer");

                    b.Property<string>("PostBodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptResultImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptResultText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ReferenceMaterialImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceMaterialText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpVotes")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Prompts", "Prompts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownVotes = 2,
                            PostBodyText = "This is the body of the first prompt.",
                            PostTitle = "First Prompt",
                            PromptResultImageUrl = "http://example.com/res1.jpg",
                            PromptResultText = "Text result for the first prompt.",
                            PromptText = "Prompt text for the first prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref1.jpg",
                            ReferenceMaterialText = "Reference text for the first prompt.",
                            UpVotes = 10,
                            UserEmail = "www.supasebie.com",
                            ViewCount = 100
                        },
                        new
                        {
                            Id = 2,
                            DownVotes = 1,
                            PostBodyText = "This is the PostBodyText of the second prompt.",
                            PostTitle = "Second Prompt",
                            PromptResultImageUrl = "http://example.com/res2.jpg",
                            PromptResultText = "Text result for the second prompt.",
                            PromptText = "Prompt text for the second prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref2.jpg",
                            ReferenceMaterialText = "Reference text for the second prompt.",
                            UpVotes = 20,
                            UserEmail = "",
                            ViewCount = 150
                        },
                        new
                        {
                            Id = 3,
                            DownVotes = 3,
                            PostBodyText = "This is the PostBodyText of the third prompt.",
                            PostTitle = "Third Prompt",
                            PromptResultImageUrl = "http://example.com/res3.jpg",
                            PromptResultText = "Text result for the third prompt.",
                            PromptText = "Prompt text for the third prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref3.jpg",
                            ReferenceMaterialText = "Reference text for the third prompt.",
                            UpVotes = 5,
                            UserEmail = "",
                            ViewCount = 50
                        },
                        new
                        {
                            Id = 4,
                            DownVotes = 0,
                            PostBodyText = "This is the PostBodyText of the fourth prompt.",
                            PostTitle = "Fourth Prompt",
                            PromptResultImageUrl = "http://example.com/res4.jpg",
                            PromptResultText = "Text result for the fourth prompt.",
                            PromptText = "Prompt text for the fourth prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref4.jpg",
                            ReferenceMaterialText = "Reference text for the fourth prompt.",
                            UpVotes = 7,
                            UserEmail = "",
                            ViewCount = 80
                        },
                        new
                        {
                            Id = 5,
                            DownVotes = 4,
                            PostBodyText = "This is the PostBodyText of the fifth prompt.",
                            PostTitle = "Fifth Prompt",
                            PromptResultImageUrl = "http://example.com/res5.jpg",
                            PromptResultText = "Text result for the fifth prompt.",
                            PromptText = "Prompt text for the fifth prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref5.jpg",
                            ReferenceMaterialText = "Reference text for the fifth prompt.",
                            UpVotes = 15,
                            UserEmail = "",
                            ViewCount = 120
                        },
                        new
                        {
                            Id = 6,
                            DownVotes = 2,
                            PostBodyText = "This is the PostBodyText of the sixth prompt.",
                            PostTitle = "Sixth Prompt",
                            PromptResultImageUrl = "http://example.com/res6.jpg",
                            PromptResultText = "Text result for the sixth prompt.",
                            PromptText = "Prompt text for the sixth prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref6.jpg",
                            ReferenceMaterialText = "Reference text for the sixth prompt.",
                            UpVotes = 8,
                            UserEmail = "",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 7,
                            DownVotes = 1,
                            PostBodyText = "This is the PostBodyText of the seventh prompt.",
                            PostTitle = "Seventh Prompt",
                            PromptResultImageUrl = "http://example.com/res7.jpg",
                            PromptResultText = "Text result for the seventh prompt.",
                            PromptText = "Prompt text for the seventh prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref7.jpg",
                            ReferenceMaterialText = "Reference text for the seventh prompt.",
                            UpVotes = 12,
                            UserEmail = "",
                            ViewCount = 110
                        },
                        new
                        {
                            Id = 8,
                            DownVotes = 3,
                            PostBodyText = "This is the PostBodyText of the eighth prompt.",
                            PostTitle = "Eighth Prompt",
                            PromptResultImageUrl = "http://example.com/res8.jpg",
                            PromptResultText = "Text result for the eighth prompt.",
                            PromptText = "Prompt text for the eighth prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref8.jpg",
                            ReferenceMaterialText = "Reference text for the eighth prompt.",
                            UpVotes = 14,
                            UserEmail = "",
                            ViewCount = 130
                        },
                        new
                        {
                            Id = 9,
                            DownVotes = 0,
                            PostBodyText = "This is the PostBodyText of the ninth prompt.",
                            PostTitle = "Ninth Prompt",
                            PromptResultImageUrl = "http://example.com/res9.jpg",
                            PromptResultText = "Text result for the ninth prompt.",
                            PromptText = "Prompt text for the ninth prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref9.jpg",
                            ReferenceMaterialText = "Reference text for the ninth prompt.",
                            UpVotes = 9,
                            UserEmail = "",
                            ViewCount = 75
                        },
                        new
                        {
                            Id = 10,
                            DownVotes = 2,
                            PostBodyText = "This is the PostBodyText of the tenth prompt.",
                            PostTitle = "Tenth Prompt",
                            PromptResultImageUrl = "http://example.com/res10.jpg",
                            PromptResultText = "Text result for the tenth prompt.",
                            PromptText = "Prompt text for the tenth prompt.",
                            ReferenceMaterialImageUrl = "http://example.com/ref10.jpg",
                            ReferenceMaterialText = "Reference text for the tenth prompt.",
                            UpVotes = 18,
                            UserEmail = "",
                            ViewCount = 140
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
