// <auto-generated />
using System;
using InPrompts.Prompts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InPrompts.Prompts.Data.Migrations
{
    [DbContext(typeof(PromptDbContext))]
    partial class PromptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Prompts")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InPrompts.Prompts.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Prompts", "Prompts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dffe455b-8f20-4b08-9ec5-3b4a1ffc4d18"),
                            Text = "What is your favorite color?",
                            User = "Daniel",
                            ViewCount = 13
                        },
                        new
                        {
                            Id = new Guid("f8e9b841-e4ad-45ed-a68c-04e5edd375fc"),
                            Text = "What is your favorite food?",
                            User = "Dom",
                            ViewCount = 13
                        },
                        new
                        {
                            Id = new Guid("bbb5a494-3ced-4e39-9bc9-59e1ac8123a1"),
                            Text = "What is your favorite movie?",
                            User = "Soren",
                            ViewCount = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
